# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
#    - task: Docker@2
#      displayName: Build an image
#      inputs:
#        command: build
#        dockerfile: '$(Build.SourcesDirectory)/src/adservice/Dockerfile'
#        tags: 'v1'

    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          docker images | grep -v REPO | head -n1 | cut -d " " -f3
#          docker images | grep -v REPO | head -n1 | awk '{print $3}'
#          docker images | grep -v REPO | head -n1| cut -d " " -f 3
#          dTag= `docker images | grep -v REPO | head -n1| awk '{print $3}'`
#          echo $dTag
#          docker tag $dTag gcr.io/aml-proj-341607:v1
    - task: Docker@2
      displayName: 'Login to Container Registry'
      inputs:
        command: login
        containerRegistry: 'gcr-sqreem'

#    - task: Docker@2
#      displayName: 'Push image'
#      inputs:
#        containerRegistry: 'gcr-sqreem'
#        repository: 'aml-proj-341607'
#        command: 'push'
#        tags: 'v1'