# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/src/adservice/Dockerfile'
        tags: 'v1'
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          docker image ls
    - task: Docker@2
      displayName: 'Login to Container Registry'
      inputs:
        command: login
        containerRegistry: 'gcr-sqreem'

    - task: Docker@2
      displayName: 'Push image'
      inputs:
        containerRegistry: 'gcr-sqreem'
        repository: 'aml-proj-341607'
        command: 'push'
        tags: 'v1'